name: Daily China Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # jeden Tag um 06:00 UTC = 07:00 MESZ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai python-dotenv requests feedparser beautifulsoup4 imapclient

      - name: Run daily briefing script
        run: python briefing.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
